--[[
  Midnight zone rare mount drops.
  Sourced from Wowhead (fetch_wowhead_item_drops.py) + HandyNotes (enrich_drop_list.py).
]]

DropTrackerCatalog:RegisterList("Midnight", DropTracker.CollectionType.mount, {
    {
        name = "Rootstalker Grimlynx",
        collectionId = 2615,
        dropItemId = 246735,
        sources = {
            {
                kind = DropTracker.SourceKind.npc,
                id = 250347,
                variant = DropTracker.Variant.world,
                chance = 5 / 4617,
                label = "Ahl'ua'huhi",
                lootLock = { type = "quest", id = 92193 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 39.66, y = 60.76 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250358,
                variant = DropTracker.Variant.world,
                chance = 4 / 2074,
                label = "Annulus the Worldshaker",
                lootLock = { type = "quest", id = 92194 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 44.42, y = 15.99 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 249844,
                variant = DropTracker.Variant.world,
                chance = 6 / 4550,
                label = "Chironex",
                lootLock = { type = "quest", id = 92137 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 68.66, y = 39.04 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 249997,
                variant = DropTracker.Variant.world,
                chance = 3 / 3889,
                label = "Chlorokyll",
                lootLock = { type = "quest", id = 92161 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 64.43, y = 47.52 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250231,
                variant = DropTracker.Variant.world,
                chance = 4 / 4494,
                label = "Dracaena",
                lootLock = { type = "quest", id = 92176 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 40.65, y = 43.13 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 249849,
                variant = DropTracker.Variant.world,
                chance = 8 / 5271,
                label = "Ha'kalawe",
                lootLock = { type = "quest", id = 92142 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 69.03, y = 59.95 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250226,
                variant = DropTracker.Variant.world,
                chance = 6 / 4376,
                label = "Mindrot",
                lootLock = { type = "quest", id = 92172 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 45.61, y = 29.69 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250317,
                variant = DropTracker.Variant.world,
                chance = 12 / 4405,
                label = "Oro'ohna",
                lootLock = { type = "quest", id = 92190 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 28.1, y = 81.83 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250321,
                variant = DropTracker.Variant.world,
                chance = 3 / 3198,
                label = "Pterrock",
                lootLock = { type = "quest", id = 92191 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 27.38, y = 71.39 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 249962,
                variant = DropTracker.Variant.world,
                chance = 11 / 5379,
                label = "Queen Lashtongue",
                lootLock = { type = "quest", id = 92154 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 59.86, y = 47.02 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 248741,
                variant = DropTracker.Variant.world,
                chance = 2 / 4996,
                label = "Rhazul",
                lootLock = { type = "quest", id = 91832 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 51.17, y = 45.34 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250180,
                variant = DropTracker.Variant.world,
                chance = 9 / 4319,
                label = "Serrasa",
                lootLock = { type = "quest", id = 92170 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 56.82, y = 34.09 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250086,
                variant = DropTracker.Variant.world,
                chance = 9 / 4779,
                label = "Stumpy",
                lootLock = { type = "quest", id = 92168 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 65.77, y = 32.86 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 249902,
                variant = DropTracker.Variant.world,
                chance = 7 / 3357,
                label = "Tallcap the Truthspreader",
                lootLock = { type = "quest", id = 92148 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 72.64, y = 69.34 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250246,
                variant = DropTracker.Variant.world,
                chance = 8 / 4026,
                label = "Treetop",
                lootLock = { type = "quest", id = 92183 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 36.56, y = 74.83 } },
            },
        },
    },
    {
        name = "Vibrant Petalwing",
        collectionId = 2708,
        dropItemId = 252012,
        sources = {
            {
                kind = DropTracker.SourceKind.npc,
                id = 250347,
                variant = DropTracker.Variant.world,
                chance = 6 / 4617,
                label = "Ahl'ua'huhi",
                lootLock = { type = "quest", id = 92193 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 39.66, y = 60.76 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250358,
                variant = DropTracker.Variant.world,
                chance = 5 / 2074,
                label = "Annulus the Worldshaker",
                lootLock = { type = "quest", id = 92194 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 44.42, y = 15.99 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 249844,
                variant = DropTracker.Variant.world,
                chance = 5 / 4550,
                label = "Chironex",
                lootLock = { type = "quest", id = 92137 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 68.66, y = 39.04 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 249997,
                variant = DropTracker.Variant.world,
                chance = 14 / 3889,
                label = "Chlorokyll",
                lootLock = { type = "quest", id = 92161 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 64.43, y = 47.52 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250231,
                variant = DropTracker.Variant.world,
                chance = 7 / 4494,
                label = "Dracaena",
                lootLock = { type = "quest", id = 92176 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 40.65, y = 43.13 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 249849,
                variant = DropTracker.Variant.world,
                chance = 8 / 5271,
                label = "Ha'kalawe",
                lootLock = { type = "quest", id = 92142 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 69.03, y = 59.95 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250226,
                variant = DropTracker.Variant.world,
                chance = 7 / 4376,
                label = "Mindrot",
                lootLock = { type = "quest", id = 92172 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 45.61, y = 29.69 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250317,
                variant = DropTracker.Variant.world,
                chance = 12 / 4405,
                label = "Oro'ohna",
                lootLock = { type = "quest", id = 92190 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 28.1, y = 81.83 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250321,
                variant = DropTracker.Variant.world,
                chance = 4 / 3198,
                label = "Pterrock",
                lootLock = { type = "quest", id = 92191 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 27.38, y = 71.39 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 249962,
                variant = DropTracker.Variant.world,
                chance = 8 / 5379,
                label = "Queen Lashtongue",
                lootLock = { type = "quest", id = 92154 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 59.86, y = 47.02 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 248741,
                variant = DropTracker.Variant.world,
                chance = 6 / 4996,
                label = "Rhazul",
                lootLock = { type = "quest", id = 91832 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 51.17, y = 45.34 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250180,
                variant = DropTracker.Variant.world,
                chance = 2 / 4319,
                label = "Serrasa",
                lootLock = { type = "quest", id = 92170 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 56.82, y = 34.09 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250086,
                variant = DropTracker.Variant.world,
                chance = 7 / 4779,
                label = "Stumpy",
                lootLock = { type = "quest", id = 92168 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 65.77, y = 32.86 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 249902,
                variant = DropTracker.Variant.world,
                chance = 7 / 3357,
                label = "Tallcap the Truthspreader",
                lootLock = { type = "quest", id = 92148 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 72.64, y = 69.34 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250246,
                variant = DropTracker.Variant.world,
                chance = 9 / 4026,
                label = "Treetop",
                lootLock = { type = "quest", id = 92183 },
                locations = { { mapId = DropTracker.Maps.midnight.harandar, x = 36.56, y = 74.83 } },
            },
        },
    },
    {
        name = "Cobalt Dragonhawk",
        collectionId = 2758,
        dropItemId = 257147,
        sources = {
            {
                kind = DropTracker.SourceKind.npc,
                id = 250841,
                variant = DropTracker.Variant.world,
                chance = 6 / 4480,
                label = "Bad Zed",
                lootLock = { type = "quest", id = 92404 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250826,
                variant = DropTracker.Variant.world,
                chance = 17 / 6479,
                label = "Banuran",
                lootLock = { type = "quest", id = 92403 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250582,
                variant = DropTracker.Variant.world,
                chance = 14 / 8322,
                label = "Bloated Snapdragon",
                lootLock = { type = "quest", id = 92366 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250683,
                variant = DropTracker.Variant.world,
                chance = 15 / 5724,
                label = "Coralfang",
                lootLock = { type = "quest", id = 92389 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250719,
                variant = DropTracker.Variant.world,
                chance = 11 / 6047,
                label = "Cre'van",
                lootLock = { type = "quest", id = 92391 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 255348,
                variant = DropTracker.Variant.world,
                chance = 12 / 8998,
                label = "Dame Bloodshed",
                lootLock = { type = "quest", id = 93561 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 255302,
                variant = DropTracker.Variant.world,
                chance = 8 / 7622,
                label = "Duskburn",
                lootLock = { type = "quest", id = 93550 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 246633,
                variant = DropTracker.Variant.world,
                chance = 13 / 7902,
                label = "Harried Hawkstrider",
                lootLock = { type = "quest", id = 91315 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250754,
                variant = DropTracker.Variant.world,
                chance = 12 / 6852,
                label = "Lady Liminus",
                lootLock = { type = "quest", id = 92393 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250806,
                variant = DropTracker.Variant.world,
                chance = 13 / 6803,
                label = "Lost Guardian",
                lootLock = { type = "quest", id = 92399 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 255329,
                variant = DropTracker.Variant.world,
                chance = 13 / 8098,
                label = "Malfunctioning Construct",
                lootLock = { type = "quest", id = 93555 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 240129,
                variant = DropTracker.Variant.world,
                chance = 11 / 5065,
                label = "Overfester Hydra",
                lootLock = { type = "quest", id = 92392 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250876,
                variant = DropTracker.Variant.world,
                chance = 5 / 4876,
                label = "Terrinor",
                lootLock = { type = "quest", id = 92409 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 246332,
                variant = DropTracker.Variant.world,
                chance = 10 / 7782,
                label = "Warden of Weeds",
                lootLock = { type = "quest", id = 91280 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250780,
                variant = DropTracker.Variant.world,
                chance = 11 / 5871,
                label = "Waverly",
                lootLock = { type = "quest", id = 92395 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
        },
    },
    {
        name = "Cerulean Hawkstrider",
        collectionId = 2762,
        dropItemId = 257156,
        sources = {
            {
                kind = DropTracker.SourceKind.npc,
                id = 250841,
                variant = DropTracker.Variant.world,
                chance = 6 / 4480,
                label = "Bad Zed",
                lootLock = { type = "quest", id = 92404 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250826,
                variant = DropTracker.Variant.world,
                chance = 10 / 6479,
                label = "Banuran",
                lootLock = { type = "quest", id = 92403 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250582,
                variant = DropTracker.Variant.world,
                chance = 13 / 8322,
                label = "Bloated Snapdragon",
                lootLock = { type = "quest", id = 92366 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250683,
                variant = DropTracker.Variant.world,
                chance = 7 / 5724,
                label = "Coralfang",
                lootLock = { type = "quest", id = 92389 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250719,
                variant = DropTracker.Variant.world,
                chance = 5 / 6047,
                label = "Cre'van",
                lootLock = { type = "quest", id = 92391 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 255348,
                variant = DropTracker.Variant.world,
                chance = 14 / 8998,
                label = "Dame Bloodshed",
                lootLock = { type = "quest", id = 93561 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 255302,
                variant = DropTracker.Variant.world,
                chance = 11 / 7622,
                label = "Duskburn",
                lootLock = { type = "quest", id = 93550 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 246633,
                variant = DropTracker.Variant.world,
                chance = 16 / 7902,
                label = "Harried Hawkstrider",
                lootLock = { type = "quest", id = 91315 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250754,
                variant = DropTracker.Variant.world,
                chance = 13 / 6852,
                label = "Lady Liminus",
                lootLock = { type = "quest", id = 92393 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250806,
                variant = DropTracker.Variant.world,
                chance = 8 / 6803,
                label = "Lost Guardian",
                lootLock = { type = "quest", id = 92399 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 255329,
                variant = DropTracker.Variant.world,
                chance = 14 / 8098,
                label = "Malfunctioning Construct",
                lootLock = { type = "quest", id = 93555 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 240129,
                variant = DropTracker.Variant.world,
                chance = 3 / 5065,
                label = "Overfester Hydra",
                lootLock = { type = "quest", id = 92392 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250876,
                variant = DropTracker.Variant.world,
                chance = 8 / 4876,
                label = "Terrinor",
                lootLock = { type = "quest", id = 92409 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 246332,
                variant = DropTracker.Variant.world,
                chance = 10 / 7782,
                label = "Warden of Weeds",
                lootLock = { type = "quest", id = 91280 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 250780,
                variant = DropTracker.Variant.world,
                chance = 5 / 5871,
                label = "Waverly",
                lootLock = { type = "quest", id = 92395 },
                locations = { { mapId = DropTracker.Maps.midnight.eversong_woods } },
            },
        },
    },
    {
        name = "Amani Sharptalon",
        collectionId = 2760,
        dropItemId = 257152,
        sources = {
            {
                kind = DropTracker.SourceKind.npc,
                id = 245692,
                variant = DropTracker.Variant.world,
                chance = 9 / 5114,
                label = "Ash'an the Empowered",
                lootLock = { type = "quest", id = 91073 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242027,
                variant = DropTracker.Variant.world,
                chance = 7 / 5664,
                label = "Depthborn Eelamental",
                lootLock = { type = "quest", id = 89573 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242026,
                variant = DropTracker.Variant.world,
                chance = 3 / 3487,
                label = "Elder Oaktalon",
                lootLock = { type = "quest", id = 89572 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242028,
                variant = DropTracker.Variant.world,
                chance = 9 / 6057,
                label = "Lightwood Borer",
                lootLock = { type = "quest", id = 89575 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 245975,
                variant = DropTracker.Variant.world,
                chance = 6 / 5214,
                label = "Mrrlokk",
                lootLock = { type = "quest", id = 91174 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242023,
                variant = DropTracker.Variant.world,
                chance = 4 / 6055,
                label = "Necrohexxer Raz'ka",
                lootLock = { type = "quest", id = 89569 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242032,
                variant = DropTracker.Variant.world,
                chance = 7 / 6902,
                label = "Oophaga",
                lootLock = { type = "quest", id = 89579 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 247976,
                variant = DropTracker.Variant.world,
                chance = 7 / 6214,
                label = "Poacher Rav'ik",
                lootLock = { type = "quest", id = 91634 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242025,
                variant = DropTracker.Variant.world,
                chance = 8 / 4938,
                label = "Skullcrusher Harak",
                lootLock = { type = "quest", id = 89571 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242031,
                variant = DropTracker.Variant.world,
                chance = 6 / 5668,
                label = "Spinefrill",
                lootLock = { type = "quest", id = 89578 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 245691,
                variant = DropTracker.Variant.world,
                chance = 7 / 3856,
                label = "The Decaying Diamondback",
                lootLock = { type = "quest", id = 91072 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242035,
                variant = DropTracker.Variant.world,
                chance = 5 / 5828,
                label = "The Devouring Invader",
                lootLock = { type = "quest", id = 89583 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242024,
                variant = DropTracker.Variant.world,
                chance = 13 / 5392,
                label = "The Snapping Scourge",
                lootLock = { type = "quest", id = 89570 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242033,
                variant = DropTracker.Variant.world,
                chance = 10 / 6289,
                label = "Tiny Vermin",
                lootLock = { type = "quest", id = 89580 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242034,
                variant = DropTracker.Variant.world,
                chance = 5 / 3981,
                label = "Voidtouched Crustacean",
                lootLock = { type = "quest", id = 89581 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
        },
    },
    {
        name = "Escaped Witherbark Pango",
        collectionId = 2775,
        dropItemId = 257200,
        sources = {
            {
                kind = DropTracker.SourceKind.npc,
                id = 245692,
                variant = DropTracker.Variant.world,
                chance = 6 / 5114,
                label = "Ash'an the Empowered",
                lootLock = { type = "quest", id = 91073 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242027,
                variant = DropTracker.Variant.world,
                chance = 11 / 5664,
                label = "Depthborn Eelamental",
                lootLock = { type = "quest", id = 89573 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242026,
                variant = DropTracker.Variant.world,
                chance = 10 / 3487,
                label = "Elder Oaktalon",
                lootLock = { type = "quest", id = 89572 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242028,
                variant = DropTracker.Variant.world,
                chance = 7 / 6057,
                label = "Lightwood Borer",
                lootLock = { type = "quest", id = 89575 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 245975,
                variant = DropTracker.Variant.world,
                chance = 5 / 5214,
                label = "Mrrlokk",
                lootLock = { type = "quest", id = 91174 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242023,
                variant = DropTracker.Variant.world,
                chance = 5 / 6055,
                label = "Necrohexxer Raz'ka",
                lootLock = { type = "quest", id = 89569 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242032,
                variant = DropTracker.Variant.world,
                chance = 6 / 6902,
                label = "Oophaga",
                lootLock = { type = "quest", id = 89579 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 247976,
                variant = DropTracker.Variant.world,
                chance = 10 / 6214,
                label = "Poacher Rav'ik",
                lootLock = { type = "quest", id = 91634 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242025,
                variant = DropTracker.Variant.world,
                chance = 7 / 4938,
                label = "Skullcrusher Harak",
                lootLock = { type = "quest", id = 89571 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242031,
                variant = DropTracker.Variant.world,
                chance = 7 / 5668,
                label = "Spinefrill",
                lootLock = { type = "quest", id = 89578 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 245691,
                variant = DropTracker.Variant.world,
                chance = 1 / 3856,
                label = "The Decaying Diamondback",
                lootLock = { type = "quest", id = 91072 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242035,
                variant = DropTracker.Variant.world,
                chance = 5 / 5828,
                label = "The Devouring Invader",
                lootLock = { type = "quest", id = 89583 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242024,
                variant = DropTracker.Variant.world,
                chance = 6 / 5392,
                label = "The Snapping Scourge",
                lootLock = { type = "quest", id = 89570 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242033,
                variant = DropTracker.Variant.world,
                chance = 8 / 6289,
                label = "Tiny Vermin",
                lootLock = { type = "quest", id = 89580 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 242034,
                variant = DropTracker.Variant.world,
                chance = 6 / 3981,
                label = "Voidtouched Crustacean",
                lootLock = { type = "quest", id = 89581 },
                locations = { { mapId = DropTracker.Maps.midnight.zulaman } },
            },
        },
    },
    {
        name = "Augmented Stormray",
        collectionId = 2751,
        dropItemId = 257085,
        sources = {
            {
                kind = DropTracker.SourceKind.npc,
                id = 248700,
                variant = DropTracker.Variant.world,
                chance = 3 / 2502,
                label = "Abysslick",
                lootLock = { type = "quest", id = 94462 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 256924,
                variant = DropTracker.Variant.world,
                chance = 4 / 4078,
                label = "Aeonelle Blackstar",
                lootLock = { type = "quest", id = 93944 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 256923,
                variant = DropTracker.Variant.world,
                chance = 10 / 3479,
                label = "Bane of the Vilebloods",
                lootLock = { type = "quest", id = 93946 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 256770,
                variant = DropTracker.Variant.world,
                chance = 8 / 4687,
                label = "Bilemaw the Gluttonous",
                lootLock = { type = "quest", id = 93884 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 248823,
                variant = DropTracker.Variant.world,
                chance = 5 / 3067,
                label = "Blackcore",
                lootLock = { type = "quest", id = 94463 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 245182,
                variant = DropTracker.Variant.world,
                chance = 4 / 1867,
                label = "Eruundi",
                lootLock = { type = "quest", id = 91047 },
                locations = { { mapId = DropTracker.Maps.midnight.slayers_rise } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 256821,
                variant = DropTracker.Variant.world,
                chance = 9 / 5210,
                label = "Far'thana the Mad",
                lootLock = { type = "quest", id = 93896 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 257231,
                variant = DropTracker.Variant.world,
                chance = 5 / 1114,
                label = "Gar'chak Skullcleave",
                lootLock = { type = "quest", id = 94461 },
                locations = { { mapId = DropTracker.Maps.midnight.slayers_rise } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 257199,
                variant = DropTracker.Variant.world,
                chance = 3 / 1120,
                label = "Hardin Steellock",
                lootLock = { type = "quest", id = 94461 },
                locations = { { mapId = DropTracker.Maps.midnight.slayers_rise } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 256925,
                variant = DropTracker.Variant.world,
                chance = 2 / 1627,
                label = "Lotus Darkblossom",
                lootLock = { type = "quest", id = 93947 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 245044,
                variant = DropTracker.Variant.world,
                chance = 3 / 4219,
                label = "Nightbrood",
                lootLock = { type = "quest", id = 91051 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 248068,
                variant = DropTracker.Variant.world,
                chance = 9 / 5335,
                label = "Nullspiral",
                lootLock = { type = "quest", id = 94460 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 256926,
                variant = DropTracker.Variant.world,
                chance = 5 / 3555,
                label = "Queen o' War",
                lootLock = { type = "quest", id = 93934 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 257027,
                variant = DropTracker.Variant.world,
                chance = 5 / 2512,
                label = "Rakshur the Bonegrinder",
                lootLock = { type = "quest", id = 93953 },
                locations = { { mapId = DropTracker.Maps.midnight.slayers_rise } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 256808,
                variant = DropTracker.Variant.world,
                chance = 3 / 1827,
                label = "Ravengerus",
                lootLock = { type = "quest", id = 93895 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 256922,
                variant = DropTracker.Variant.world,
                chance = 2 / 1705,
                label = "Screammaxa the Matriarch",
                lootLock = { type = "quest", id = 93966 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 244272,
                variant = DropTracker.Variant.world,
                chance = 12 / 5044,
                label = "Sundereth the Caller",
                lootLock = { type = "quest", id = 90805 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 238498,
                variant = DropTracker.Variant.world,
                chance = 3 / 3448,
                label = "Territorial Voidscythe",
                lootLock = { type = "quest", id = 91050 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 248459,
                variant = DropTracker.Variant.world,
                chance = 4 / 3808,
                label = "The Many-Broken",
                lootLock = { type = "quest", id = 94458 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 241443,
                variant = DropTracker.Variant.world,
                chance = 4 / 2419,
                label = "Tremora",
                lootLock = { type = "quest", id = 91048 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 248791,
                variant = DropTracker.Variant.world,
                chance = 10 / 6641,
                label = "Voidseer Orivane",
                lootLock = { type = "quest", id = 94459 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
        },
    },
    {
        name = "Sanguine Harrower",
        collectionId = 2827,
        dropItemId = 260635,
        sources = {
            {
                kind = DropTracker.SourceKind.npc,
                id = 248700,
                variant = DropTracker.Variant.world,
                chance = 4 / 2502,
                label = "Abysslick",
                lootLock = { type = "quest", id = 94462 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 256924,
                variant = DropTracker.Variant.world,
                chance = 7 / 4078,
                label = "Aeonelle Blackstar",
                lootLock = { type = "quest", id = 93944 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 256923,
                variant = DropTracker.Variant.world,
                chance = 6 / 3479,
                label = "Bane of the Vilebloods",
                lootLock = { type = "quest", id = 93946 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 256770,
                variant = DropTracker.Variant.world,
                chance = 2 / 4687,
                label = "Bilemaw the Gluttonous",
                lootLock = { type = "quest", id = 93884 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 248823,
                variant = DropTracker.Variant.world,
                chance = 8 / 3067,
                label = "Blackcore",
                lootLock = { type = "quest", id = 94463 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 245182,
                variant = DropTracker.Variant.world,
                chance = 1 / 1867,
                label = "Eruundi",
                lootLock = { type = "quest", id = 91047 },
                locations = { { mapId = DropTracker.Maps.midnight.slayers_rise } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 256821,
                variant = DropTracker.Variant.world,
                chance = 5 / 5210,
                label = "Far'thana the Mad",
                lootLock = { type = "quest", id = 93896 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 257231,
                variant = DropTracker.Variant.world,
                chance = 5 / 1114,
                label = "Gar'chak Skullcleave",
                lootLock = { type = "quest", id = 94461 },
                locations = { { mapId = DropTracker.Maps.midnight.slayers_rise } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 257199,
                variant = DropTracker.Variant.world,
                chance = 2 / 1120,
                label = "Hardin Steellock",
                lootLock = { type = "quest", id = 94461 },
                locations = { { mapId = DropTracker.Maps.midnight.slayers_rise } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 256925,
                variant = DropTracker.Variant.world,
                chance = 9 / 1627,
                label = "Lotus Darkblossom",
                lootLock = { type = "quest", id = 93947 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 245044,
                variant = DropTracker.Variant.world,
                chance = 2 / 4219,
                label = "Nightbrood",
                lootLock = { type = "quest", id = 91051 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 248068,
                variant = DropTracker.Variant.world,
                chance = 5 / 5335,
                label = "Nullspiral",
                lootLock = { type = "quest", id = 94460 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 256926,
                variant = DropTracker.Variant.world,
                chance = 7 / 3555,
                label = "Queen o' War",
                lootLock = { type = "quest", id = 93934 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 257027,
                variant = DropTracker.Variant.world,
                chance = 4 / 2512,
                label = "Rakshur the Bonegrinder",
                lootLock = { type = "quest", id = 93953 },
                locations = { { mapId = DropTracker.Maps.midnight.slayers_rise } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 256808,
                variant = DropTracker.Variant.world,
                chance = 1 / 1827,
                label = "Ravengerus",
                lootLock = { type = "quest", id = 93895 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 256922,
                variant = DropTracker.Variant.world,
                chance = 3 / 1705,
                label = "Screammaxa the Matriarch",
                lootLock = { type = "quest", id = 93966 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 244272,
                variant = DropTracker.Variant.world,
                chance = 9 / 5044,
                label = "Sundereth the Caller",
                lootLock = { type = "quest", id = 90805 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 238498,
                variant = DropTracker.Variant.world,
                chance = 8 / 3448,
                label = "Territorial Voidscythe",
                lootLock = { type = "quest", id = 91050 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 248459,
                variant = DropTracker.Variant.world,
                chance = 3 / 3808,
                label = "The Many-Broken",
                lootLock = { type = "quest", id = 94458 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 241443,
                variant = DropTracker.Variant.world,
                chance = 4 / 2419,
                label = "Tremora",
                lootLock = { type = "quest", id = 91048 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 248791,
                variant = DropTracker.Variant.world,
                chance = 8 / 6641,
                label = "Voidseer Orivane",
                lootLock = { type = "quest", id = 94459 },
                locations = { { mapId = DropTracker.Maps.midnight.voidstorm } },
            },
        },
    },
    {
        name = "Ashes of Belo'ren",
        collectionId = 2607,
        dropItemId = 246590,
        sources = {
            {
                kind = DropTracker.SourceKind.encounter,
                id = 3183,
                variant = DropTracker.Variant.mythic,
                chance = 2 / 20,
                label = "Midnight Falls",
                locations = { { mapId = DropTracker.Maps.midnight.march_on_queldanas } },
            },
        },
    },
    {
        name = "Lucent Hawkstrider",
        collectionId = 2817,
        dropItemId = 260231,
        sources = {
            {
                kind = DropTracker.SourceKind.item,
                id = 574407,
                variant = DropTracker.Variant.mythic,
                chance = 127 / 6318,
                label = "Challenger's Cache",
                statId = 61217,
                locations = { { mapId = DropTracker.Maps.midnight.magisters_terrace } },
            },
        },
    },
    {
        name = "Spectral Hawkstrider",
        collectionId = 2805,
        dropItemId = 262914,
        sources = {
            {
                kind = DropTracker.SourceKind.item,
                id = 574408,
                variant = DropTracker.Variant.mythic,
                chance = 196 / 9661,
                label = "Challenger's Cache",
                statId = 41295,
                locations = { { mapId = DropTracker.Maps.midnight.windrunner_spire } },
            },
        },
    },
    {
        name = "Duskbrute Harrower",
        collectionId = 2764,
        dropItemId = 257176,
        listGroup = DropTracker.ListGroup.paragon,
        sources = {
            {
                kind = DropTracker.SourceKind.item,
                id = 267299,
                variant = DropTracker.Variant.world,
                chance = 29 / 98,
                label = "Slayer's Duellum Trove",
                paragon = true,
                locations = { { mapId = DropTracker.Maps.midnight.slayers_rise } },
            },
        },
    },
})
