--[[
  The War Within mount drops: world rares, raids, dungeons, paragon troves.
  Sourced from Wowhead (fetch_wowhead_item_drops.py) + HandyNotes (11_TheWarWithin).
]]

DropTrackerCatalog:RegisterList("TheWarWithin", DropTracker.CollectionType.mount, {
    {
        name = "Alunira",
        collectionId = 2176,
        dropItemId = 223270,
        sources = {
            {
                kind = DropTracker.SourceKind.npc,
                id = 219281,
                variant = DropTracker.Variant.world,
                chance = 406 / 632,
                label = "Alunira",
                lootLock = { type = "quest", id = 82196 },
                locations = { { mapId = DropTracker.Maps.the_war_within.isle_of_dorn, x = 23.33, y = 58.17 } },
            },
        },
    },
    {
        name = "Beledar's Spawn",
        collectionId = 2192,
        dropItemId = 223315,
        sources = {
            {
                kind = DropTracker.SourceKind.npc,
                id = 207802,
                variant = DropTracker.Variant.world,
                chance = 1344 / 24338,
                label = "Beledar's Spawn",
                lootLock = { type = "quest", id = 81763 },
                locations = { { mapId = DropTracker.Maps.the_war_within.hallowfall, x = 25.0, y = 45.0 } },
            },
        },
    },
    {
        name = "Ol' Mole Rufus",
        collectionId = 2205,
        dropItemId = 223501,
        sources = {
            {
                kind = DropTracker.SourceKind.npc,
                id = 220285,
                variant = DropTracker.Variant.world,
                chance = 131 / 2189,
                label = "Lurker of the Deeps",
                lootLock = { type = "quest", id = 81633 },
                locations = { { mapId = DropTracker.Maps.the_war_within.ringing_deeps, x = 56.72, y = 76.68 } },
            },
        },
    },
    {
        name = "Darkfuse Spy-Eye",
        collectionId = 2293,
        dropItemId = 229955,
        sources = {
            {
                kind = DropTracker.SourceKind.npc,
                id = 231310,
                variant = DropTracker.Variant.world,
                chance = 58 / 1342,
                label = "Darkfuse Precipitant",
                lootLock = { type = "quest", id = 90492 },
                locations = { { mapId = DropTracker.Maps.the_war_within.undermine, x = 40.2, y = 91.9 } },
            },
        },
    },
    {
        name = "Sthaarbs's Last Lunch",
        collectionId = 2603,
        dropItemId = 246160,
        sources = {
            {
                kind = DropTracker.SourceKind.npc,
                id = 234845,
                variant = DropTracker.Variant.world,
                chance = 346 / 5059,
                label = "Sthaarbs",
                lootLock = { type = "quest", id = 91293 },
                locations = { { mapId = DropTracker.Maps.the_war_within.karesh, x = 74.04, y = 32.54 } },
            },
        },
    },
    {
        name = "Pearlescent Krolusk",
        collectionId = 2601,
        dropItemId = 246067,
        sources = {
            {
                kind = DropTracker.SourceKind.npc,
                id = 232195,
                variant = DropTracker.Variant.world,
                chance = 654 / 8151,
                label = "Urmag",
                lootLock = { type = "quest", id = 90593 },
                locations = { { mapId = DropTracker.Maps.the_war_within.karesh, x = 70.14, y = 49.83 } },
            },
        },
    },
    {
        name = "Translocated Gorger",
        collectionId = 2602,
        dropItemId = 246159,
        sources = {
            {
                kind = DropTracker.SourceKind.npc,
                id = 231229,
                variant = DropTracker.Variant.world,
                chance = 74 / 4637,
                label = "Korgoth the Hungerer",
                lootLock = { type = "quest", id = 84993 },
                locations = { { mapId = DropTracker.Maps.the_war_within.karesh, x = 71.4, y = 27.6 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 234970,
                variant = DropTracker.Variant.world,
                chance = 201 / 10731,
                label = "Miasmawrath",
                lootLock = { type = "quest", id = 86447 },
                locations = { { mapId = DropTracker.Maps.the_war_within.karesh, x = 50.6, y = 54.1 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 235087,
                variant = DropTracker.Variant.world,
                chance = 149 / 9491,
                label = "The Harvester",
                lootLock = { type = "quest", id = 86464 },
                locations = { { mapId = DropTracker.Maps.the_war_within.karesh, x = 49.5, y = 64.2 } },
            },
            {
                kind = DropTracker.SourceKind.npc,
                id = 235104,
                variant = DropTracker.Variant.world,
                chance = 152 / 8436,
                label = "The Wallbreaker",
                lootLock = { type = "quest", id = 86465 },
                locations = { { mapId = DropTracker.Maps.the_war_within.tazavesh, x = 27.5, y = 72.3 } },
            },
        },
    },
    {
        name = "Sureki Skyrazor",
        collectionId = 2219,
        dropItemId = 224147,
        sources = {
            {
                kind = DropTracker.SourceKind.encounter,
                id = 2922,
                variant = DropTracker.Variant.lfr,
                chance = 1 / 100,
                statId = 40295,
                label = "Queen Ansurek",
                locations = { { mapId = DropTracker.Maps.the_war_within.nerub_ar_palace } },
            },
            {
                kind = DropTracker.SourceKind.encounter,
                id = 2922,
                variant = DropTracker.Variant.normal,
                chance = 1 / 100,
                statId = 40296,
                label = "Queen Ansurek",
                locations = { { mapId = DropTracker.Maps.the_war_within.nerub_ar_palace } },
            },
            {
                kind = DropTracker.SourceKind.encounter,
                id = 2922,
                variant = DropTracker.Variant.heroic,
                chance = 1 / 100,
                statId = 40297,
                label = "Queen Ansurek",
                locations = { { mapId = DropTracker.Maps.the_war_within.nerub_ar_palace } },
            },
            {
                kind = DropTracker.SourceKind.encounter,
                id = 2922,
                variant = DropTracker.Variant.mythic,
                chance = 1 / 100,
                statId = 40298,
                label = "Queen Ansurek",
                locations = { { mapId = DropTracker.Maps.the_war_within.nerub_ar_palace } },
            },
        },
    },
    {
        name = "Ascendant Skyrazor",
        collectionId = 2223,
        dropItemId = 224151,
        sources = {
            {
                kind = DropTracker.SourceKind.encounter,
                id = 2922,
                variant = DropTracker.Variant.mythic,
                chance = 1 / 100,
                statId = 40298,
                label = "Queen Ansurek",
                locations = { { mapId = DropTracker.Maps.the_war_within.nerub_ar_palace } },
            },
        },
    },
    {
        name = "Prototype A.S.M.R.",
        collectionId = 2507,
        dropItemId = 236960,
        sources = {
            {
                kind = DropTracker.SourceKind.encounter,
                id = 3016,
                variant = DropTracker.Variant.lfr,
                chance = 1 / 100,
                statId = 41327,
                label = "Chrome King Gallywix",
                locations = { { mapId = DropTracker.Maps.the_war_within.liberation_of_undermine } },
            },
            {
                kind = DropTracker.SourceKind.encounter,
                id = 3016,
                variant = DropTracker.Variant.normal,
                chance = 1 / 100,
                statId = 41328,
                label = "Chrome King Gallywix",
                locations = { { mapId = DropTracker.Maps.the_war_within.liberation_of_undermine } },
            },
            {
                kind = DropTracker.SourceKind.encounter,
                id = 3016,
                variant = DropTracker.Variant.heroic,
                chance = 1 / 100,
                statId = 41329,
                label = "Chrome King Gallywix",
                locations = { { mapId = DropTracker.Maps.the_war_within.liberation_of_undermine } },
            },
            {
                kind = DropTracker.SourceKind.encounter,
                id = 3016,
                variant = DropTracker.Variant.mythic,
                chance = 1 / 100,
                statId = 41330,
                label = "Chrome King Gallywix",
                locations = { { mapId = DropTracker.Maps.the_war_within.liberation_of_undermine } },
            },
        },
    },
    {
        name = "The Big G",
        collectionId = 2487,
        dropItemId = 235626,
        sources = {
            {
                kind = DropTracker.SourceKind.encounter,
                id = 3016,
                variant = DropTracker.Variant.mythic,
                chance = 1 / 100,
                statId = 41330,
                label = "Chrome King Gallywix",
                locations = { { mapId = DropTracker.Maps.the_war_within.liberation_of_undermine } },
            },
        },
    },
    {
        name = "Unbound Star-Eater",
        collectionId = 2569,
        dropItemId = 243061,
        sources = {
            {
                kind = DropTracker.SourceKind.encounter,
                id = 3135,
                variant = DropTracker.Variant.mythic,
                chance = 1 / 100,
                statId = 41664,
                label = "Dimensius, the All-Devouring",
                locations = { { mapId = DropTracker.Maps.the_war_within.manaforge_omega } },
            },
        },
    },
    {
        name = "Stonevault Mechsuit",
        collectionId = 2119,
        dropItemId = 221765,
        sources = {
            {
                kind = DropTracker.SourceKind.encounter,
                id = 2883,
                variant = DropTracker.Variant.mythic,
                contentType = DropTracker.SourceContentType.dungeon,
                chance = 78 / 25686,
                label = "Void Speaker Eirich",
                locations = { { mapId = DropTracker.Maps.the_war_within.stonevault } },
            },
        },
    },
    {
        name = "Wick's Lead",
        collectionId = 2204,
        dropItemId = 225548,
        sources = {
            {
                kind = DropTracker.SourceKind.encounter,
                id = 2788,
                variant = DropTracker.Variant.mythic,
                contentType = DropTracker.SourceContentType.dungeon,
                chance = 449 / 15387,
                label = "The Darkness",
                locations = { { mapId = DropTracker.Maps.the_war_within.darkflame_cleft } },
            },
        },
    },
    {
        name = "Bilgewater Bombardier",
        collectionId = 2295,
        dropItemId = 229957,
        listGroup = DropTracker.ListGroup.paragon,
        sources = {
            {
                kind = DropTracker.SourceKind.item,
                id = 237132,
                variant = DropTracker.Variant.world,
                chance = 1 / 20,
                label = "Bilgewater Trove",
                paragon = true,
                locations = { { mapId = DropTracker.Maps.the_war_within.undermine } },
            },
        },
    },
    {
        name = "Venture Co-ordinator",
        collectionId = 2289,
        dropItemId = 229951,
        listGroup = DropTracker.ListGroup.paragon,
        sources = {
            {
                kind = DropTracker.SourceKind.item,
                id = 237133,
                variant = DropTracker.Variant.world,
                chance = 1 / 20,
                label = "Venture Co. Trove",
                paragon = true,
                locations = { { mapId = DropTracker.Maps.the_war_within.undermine } },
            },
        },
    },
    {
        name = "Steamwheedle Supplier",
        collectionId = 2281,
        dropItemId = 229943,
        listGroup = DropTracker.ListGroup.paragon,
        sources = {
            {
                kind = DropTracker.SourceKind.item,
                id = 237134,
                variant = DropTracker.Variant.world,
                chance = 1 / 20,
                label = "Steamwheedle Trove",
                paragon = true,
                locations = { { mapId = DropTracker.Maps.the_war_within.undermine } },
            },
        },
    },
    {
        name = "Blackwater Bonecrusher",
        collectionId = 2274,
        dropItemId = 229937,
        listGroup = DropTracker.ListGroup.paragon,
        sources = {
            {
                kind = DropTracker.SourceKind.item,
                id = 237135,
                variant = DropTracker.Variant.world,
                chance = 1 / 20,
                label = "Blackwater Trove",
                paragon = true,
                locations = { { mapId = DropTracker.Maps.the_war_within.undermine } },
            },
        },
    },
    {
        name = "Bronze Goblin Waveshredder",
        collectionId = 2334,
        dropItemId = 233064,
        listGroup = DropTracker.ListGroup.paragon,
        sources = {
            {
                kind = DropTracker.SourceKind.item,
                id = 232465,
                variant = DropTracker.Variant.world,
                chance = 1 / 20,
                label = "Darkfuse Trove",
                paragon = true,
                locations = { { mapId = DropTracker.Maps.the_war_within.undermine } },
            },
        },
    },
})
